// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: proto/compiler.proto

package compilerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TexSource     string                 `protobuf:"bytes,1,opt,name=tex_source,json=texSource,proto3" json:"tex_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_proto_compiler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compiler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_proto_compiler_proto_rawDescGZIP(), []int{0}
}

func (x *CompileRequest) GetTexSource() string {
	if x != nil {
		return x.TexSource
	}
	return ""
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pdf           []byte                 `protobuf:"bytes,1,opt,name=pdf,proto3" json:"pdf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_proto_compiler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compiler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_proto_compiler_proto_rawDescGZIP(), []int{1}
}

func (x *CompileResponse) GetPdf() []byte {
	if x != nil {
		return x.Pdf
	}
	return nil
}

var File_proto_compiler_proto protoreflect.FileDescriptor

const file_proto_compiler_proto_rawDesc = "" +
	"\n" +
	"\x14proto/compiler.proto\x12\x14resumakr.compiler.v1\"/\n" +
	"\x0eCompileRequest\x12\x1d\n" +
	"\n" +
	"tex_source\x18\x01 \x01(\tR\ttexSource\"#\n" +
	"\x0fCompileResponse\x12\x10\n" +
	"\x03pdf\x18\x01 \x01(\fR\x03pdf2b\n" +
	"\bCompiler\x12V\n" +
	"\aCompile\x12$.resumakr.compiler.v1.CompileRequest\x1a%.resumakr.compiler.v1.CompileResponseB(Z&jakes-resume-compiler/proto/compilerpbb\x06proto3"

var (
	file_proto_compiler_proto_rawDescOnce sync.Once
	file_proto_compiler_proto_rawDescData []byte
)

func file_proto_compiler_proto_rawDescGZIP() []byte {
	file_proto_compiler_proto_rawDescOnce.Do(func() {
		file_proto_compiler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compiler_proto_rawDesc), len(file_proto_compiler_proto_rawDesc)))
	})
	return file_proto_compiler_proto_rawDescData
}

var file_proto_compiler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_compiler_proto_goTypes = []any{
	(*CompileRequest)(nil),  // 0: resumakr.compiler.v1.CompileRequest
	(*CompileResponse)(nil), // 1: resumakr.compiler.v1.CompileResponse
}
var file_proto_compiler_proto_depIdxs = []int32{
	0, // 0: resumakr.compiler.v1.Compiler.Compile:input_type -> resumakr.compiler.v1.CompileRequest
	1, // 1: resumakr.compiler.v1.Compiler.Compile:output_type -> resumakr.compiler.v1.CompileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_compiler_proto_init() }
func file_proto_compiler_proto_init() {
	if File_proto_compiler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compiler_proto_rawDesc), len(file_proto_compiler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_compiler_proto_goTypes,
		DependencyIndexes: file_proto_compiler_proto_depIdxs,
		MessageInfos:      file_proto_compiler_proto_msgTypes,
	}.Build()
	File_proto_compiler_proto = out.File
	file_proto_compiler_proto_goTypes = nil
	file_proto_compiler_proto_depIdxs = nil
}
